theme: jekyll-theme-cayman
title: 'app-page-tempalte'
description: 'A github page template for app'
# google_analytics: G-NWQY9CVPF7

show_ios_download_btn: true
ios_download_url: 'https://www.apple.com/'
ios_download_btn_title: 'Download from App Store'

show_android_download_btn: true
android_download_url: 'https://www.google.com'
android_download_btn_title: 'Download from Google Play'

show_web_download_btn: true
web_download_url: 'https://www.google.com'
web_download_btn_title: 'Download .dmg'

show_email_link: true
email: 'example@example.com'

show_terms_link: true
terms_link: 'terms'

show_privacy_link: true
privacy_link: 'privacy'

copyright: 'Copyright Group-Leafy. All rights reserved'

show_app_icon: true
app_icon: 'assets/image/icon.png'

show_screenshot: true
screenshots: ['assets/image/screenshot.png', 'assets/image/screenshot.png', 'assets/image/screenshot.png', 'assets/image/screenshot.png', 'assets/image/screenshot.png']