theme: jekyll-theme-cayman
title: 'Dr.EXIF'
description: 'A photo info viewer with documentation'
# google_analytics: G-NWQY9CVPF7

show_ios_download_btn: true
ios_download_url: 'https://apps.apple.com/us/app/id1543861410'
ios_download_btn_title: 'Download from App Store'

show_android_download_btn: false
android_download_url: 'https://www.google.com'
android_download_btn_title: 'Download from Google Play'

show_web_download_btn: false
web_download_url: 'https://www.google.com'
web_download_btn_title: 'Download .dmg'

show_email_link: true
email: 'group.leafy@gmail.com'

show_terms_link: true
terms_link: 'terms'

show_privacy_link: true
privacy_link: 'privacy'

copyright: 'Copyright Group-Leafy. All rights reserved'

show_app_icon: true
app_icon: 'assets/image/icon.png'

show_screenshot: true
screenshots: ['assets/image/screenshot1.png', 'assets/image/screenshot2.png', 'assets/image/screenshot3.png', 'assets/image/screenshot4.png', 'assets/image/screenshot5.png', 'assets/image/screenshot6.png']